namespace Warehouse.Core.Entities;

public class Product
{
    public int Id { get; set; } // Unique identifier of the product
    public string Name { get; set; } // Name of the product
    public int Price { get; set; } // Price of the product in cents
    public string Descryption { get; set; } // Product's description
    public string ImageUrl { get; set; } // Path or URL to the product's image
    public string Barcode { get; set; } // Product's barcode; must be generated by system if blank
    public int UnitId { get; set; } // Identifier of the unit of measurement in which the product is sold (e.g., piece, kilogram, liter)
    public int CategoryId { get; set; } // Identifier of the category to which the product belongs
    public bool Active { get; set; } // Indicates if the product is active or inactive
    public DateTime CreateDate { get; set; } // Date and time when the product was created
    public DateTime UpdateDate { get; set; } // Date and time when the product was last updated
}