version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: dotwarehouse_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Comput4dor      # senha do root
      MYSQL_DATABASE: dotwarehouse      # nome do banco
      MYSQL_USER: julio                  # usuário normal
      MYSQL_PASSWORD: Comput4dor           # senha do usuário
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:Z  # scripts de inicialização

volumes:
  db_data:
