//file: backend/Warehouse.Core/Inventory/Entities/Product.cs

namespace Warehouse.Core.Entities
{
    public class Product
    {
        public int Id { get; set; } // Unique identifier of the product
        public string Name { get; set; } // Name of the product
        public int Price { get; set; } // Price of the product in cents
        public string Description { get; set; } // Product's description
        public string ImageUrl { get; set; } // Path or URL to the product's image
        public string Barcode { get; set; } // Product's barcode; must be generated by system if blank
        public int UnitId { get; set; } // Identifier of the unit of measurement
        public int CategoryId { get; set; } // Identifier of the category
        public bool Active { get; set; } // Indicates if the product is active or inactive
        public DateTime CreateDate { get; set; } // Date and time when the product was created
        public DateTime UpdateDate { get; set; } // Date and time when the product was last updated

        // Navigation properties
        public Unit Unit { get; set; } = null!;
        public Category Category { get; set; } = null!;
        public ICollection<Movement> Movements { get; set; } = new List<Movement>();
        public ICollection<ProductSupplier> ProductSuppliers { get; set; } = new List<ProductSupplier>();
    }


}
